version: '3'

services:
  app:
    build: .
    container_name: user-management-app
    expose:
      - 3000
    environment:
      - PG_URL=${PG_URL}
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6-alpine
    container_name: postgres
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_USER=dios
      - POSTGRES_PASSWORD=dios
      - POSTGRES_DB=test
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: